language: cpp
compiler:
    - clang
    - gcc
install:
    - sudo apt-get update
    - sudo apt-get install -y libcunit1 libcunit1-dev libglfw-dev libglew-dev xorg-dev
script:
    - make
    - make test
