language: cpp
compiler:
    - clang
    - g++
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - wget http://www.cmake.org/files/v3.1/cmake-3.1.2-Linux-x86_64.sh
    - chmod +x cmake-3.1.2-Linux-x86_64.sh
    - mkdir cmake
install:
    - sudo apt-get install -y -qq libcunit1 libcunit1-dev libglfw-dev libglew-dev xorg-dev gcc-4.8 g++-4.8 libiniparser-dev
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
# libglfw3 isn't up to date in apt with precise
    - wget 'http://sourceforge.net/projects/glfw/files/glfw/3.0.4/glfw-3.0.4.zip'
    - unzip glfw-3.0.4.zip
    - cd glfw-3.0.4 && cmake -DBUILD_SHARED_LIBS=ON -G "Unix Makefiles" && make && sudo make install
    - sudo cp /usr/local/lib/libglfw* /usr/lib/ && sudo cp -R /usr/local/include/GLFW /usr/include/
    - cd ..
    - sh cmake-3.1.2-Linux-x86_64.sh --skip-license --prefix=cmake --exclude-subdir
script:
    - cmake/bin/cmake .
    - make && make test
