language: cpp
compiler:
    - clang
    - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - gcc-4.9
      - g++-4.9
      - clang-3.7
install:
    - sudo apt-get install -y -qq libcunit1 libcunit1-dev libglfw-dev libglew-dev libfreeimage-dev xorg-dev
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
    - sh ./setup-dependencies.sh
script:
    - cmake/bin/cmake .
    - make && make test
