FIND_PATH(FREEIMAGE_INCLUDE_DIR NAMES FreeImage.h)
MARK_AS_ADVANCED(FREEIMAGE_INCLUDE_DIR)

FIND_LIBRARY(FREEIMAGE_LIBRARY NAMES
    freeimage
    libfreefmage
    freeimagelib
)
MARK_AS_ADVANCED(FREEIMAGE_LIBRARY)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FreeImage DEFAULT_MSG FREEIMAGE_LIBRARY FREEIMAGE_INCLUDE_DIR)

IF(FREEIMAGE_FOUND)
  SET(FREEIMAGE_LIBRARIES ${FREEIMAGE_LIBRARY})
  SET(FREEIMAGE_INCLUDE_DIRS ${FREEIMAGE_INCLUDE_DIR})
ENDIF(FREEIMAGE_FOUND)
