FIND_PATH(INIPARSER_INCLUDE_DIR NAMES iniparser.h)
MARK_AS_ADVANCED(INIPARSER_INCLUDE_DIR)

FIND_LIBRARY(INIPARSER_LIBRARY NAMES
    iniparser
    libiniparser
    iniparserlib
)
MARK_AS_ADVANCED(INIPARSER_LIBRARY)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(iniparser DEFAULT_MSG INIPARSER_LIBRARY INIPARSER_INCLUDE_DIR)

IF(INIPARSER_FOUND)
  SET(INIPARSER_LIBRARIES ${INIPARSER_LIBRARY})
  SET(INIPARSER_INCLUDE_DIRS ${INIPARSER_INCLUDE_DIR})
ENDIF(INIPARSER_FOUND)
